### ISSUE TITLE
Socket gets closed in background mode

### ISSUE THREAD

**Issue by mitos14** [nuclearace/Socket.IO-Client-Swift#1]
Hi,
Thank you for this great lib. I am trying to receive socket.io notification while my app is in background. However, it seems that the socket.io client is suspended till the application comes back to foreground. I have tried enabling pretty much all background modes in plist and Application Capabilities Background modes. None of this works.
App goes in background and I no longer get messages till the app comes to foreground.

Any help with this would be appreciated. 
Thank you

**Comment by blackbumer** [comment]
It might be possible with voip entitlements but need be tested

**Comment by nuclearace** [comment]
If anyone has any input, I'd be glad to hear it, until then I'm closing issue.
