### ISSUE TITLE
using websockets and swift

### ISSUE THREAD

**Issue by zglozman** [nuclearace/Socket.IO-Client-Swift#101]
When using 

        self.socket = SocketIOClient(socketURL: self.endPoint, options: [.Log(false), .Nsp("/TcpServerWS"), ])

I get this from 
![image](https://cloud.githubusercontent.com/assets/11706909/11885201/4e783ae0-a528-11e5-90ad-a9aae0232e10.png) which is clearly using polling which is not what i want 

or if i use ForceWebsockets it just does this and sever does not get connect event, what can i do ?
![image](https://cloud.githubusercontent.com/assets/11706909/11885226/79835440-a528-11e5-974b-e4e6f463c3f0.png)

**Comment by nuclearace** [comment]
If you don't force polling the client should automatically upgrade to websockets. What server are you using? I know there was a version of a python based server that didn't properly handle a forced websockets connection.

**Comment by zglozman** [comment]
node.js with the most standard configuration 
var debug = require('debug')('http')
var app = require('http').createServer(handler)
var io = require('socket.io')(app);
var fs = require('fs');
var Logger = require('socket.io-logger')();


io.use(Logger);
function handler (req, res) {
    res.end('Error loading index.html');
    res.writeHead(200);
    res.end(data);
}

app.listen(8108);
var tcpProxyServer = require('../src/TcpProxyServer');
// or pass no server and then you can call the method

io.serveClient(false);
io.attach(app);

var proxy = new tcpProxyServer(io, "127.0.0.1");
proxy.init();

**Comment by nuclearace** [comment]
My guess it's something to do with that proxy server. Have you tried the JS client from a browser?

**Comment by zglozman** [comment]
will try no, but my guess it will work, its something on ios side, maybe no websocket w/o ssl ?

**Comment by nuclearace** [comment]
For your pics it doesn't look like it's trying to use HTTPS.

**Comment by zglozman** [comment]
i understand but maybe i should ?

**Comment by nuclearace** [comment]
iOS 9 is a lot stricter about connections and TLS, so maybe.

**Comment by nuclearace** [comment]
Was this resolved?

**Comment by zglozman** [comment]
And essentially i dont know what i did. the problem is on the swift side.
