### ISSUE TITLE
Cannot connect to Node.js server on Heroku 

### ISSUE THREAD

**Issue by jSchapiroAtTheMelt** [nuclearace/Socket.IO-Client-Swift#110]
My Node Code: 

'use strict';
let bodyParser = require('body-parser');
let morgan = require('morgan');
let ParseCloud = require('parse-cloud-express');
let Parse = ParseCloud.Parse;
let Mosaic = require('../Mosaic/Mosaic.js');
let Contribution = require('../Mosaic/Contribution.js');

module.exports = (app) => {

  let server = require('http').Server(app);
  let io = require('socket.io')(server);
  server.listen(process.env.PORT || 8080); //expose port 8080

My iOS code:

 
        socket = SocketIOClient(socketURL: NSURL(string: "mosaiek.herokuapp.com:8080")!, options: [ .ForcePolling(true), .Log(true)])
        
        socket!.on("connect") {data, ack in
            print("socket connected")
        }

Works fine on localhost but not when deployed :(

**Comment by nuclearace** [comment]
Make sure the URL you're using is the actual url of the socket.io server.

**Comment by jSchapiroAtTheMelt** [comment]
This was the working url string: http://mosaiek.herokuapp.com
no port
