### ISSUE TITLE
Doesn't immediately close

### ISSUE THREAD

**Issue by jeon97** [nuclearace/Socket.IO-Client-Swift#12]
There seems to be a delay in closing the socket. After i call socket.close(), the socket is still open for a while and finally after a few minutes I can see that it disconnected on my server.

**Comment by nuclearace** [comment]
Are you calling socket.close on some sort of dispatchQueue?

**Comment by jeon97** [comment]
no i'm calling it in 

    func applicationDidEnterBackground(application: UIApplication!) {
        io.close()
        print("applicationDidEnterBackground")
    }

**Comment by nuclearace** [comment]
Well, you need to put that into background task. Something like 

![](http://i.imgur.com/5Wrfhec.png)

Which either is just socket.close() or like the pic, does additional shutdown and calls it.

**Comment by jeon97** [comment]
I tried your solution, but unfortunately still the same issue. The on disconnect is fired immediately on the client side, but on the server side, there is a delay of a few minutes just with the disconnect function. All the other events are fired immediately, but just the disconnect is slow.

**Comment by nuclearace** [comment]
I'll look into it

**Comment by nuclearace** [comment]
Check and see if it's fixed in latest commit

**Comment by waphumanoid** [comment]
Hi. I am using current master branch and facing the same problem - I am trying to close the socket in a background process (for testing purposes in 5 secs  after "open" using dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)...) and the disconnect event is fired only after a minute.

Here is some log:
2015-03-24 10:58:03.160
Should do event: "connect" with data: "nil"
2015-03-24 10:58:05.372
Sending ws: probe as type: 2
Sending ws:  as type: 5
2015-03-24 10:58:09.035
Sending ws: 1 as type: 4
...
2015-03-24 10:59:08.896
Should do event: "disconnect" with data: "Optional([WebSocket closed])"

**Comment by nuclearace** [comment]
I'll look into it
