### ISSUE TITLE
Fallback to XHR polling?

### ISSUE THREAD

**Issue by naartjie** [nuclearace/Socket.IO-Client-Swift#13]
I'm not even sure if this is necessary on native mobile platforms, but is it not possible that the phone is connected to a wi-fi network which only allows HTTP traffic, and blocks WS connections? In such cases it would be nice to fallback to XHR / long polling, right?

I see these projects both have done something along those lines:
https://github.com/francoisp/socket.IO-objc
https://github.com/shuoli84/SocketIOCocoa

This project definitely has the nicest API out of all that I have seen, so I wanted to try it first and see how I go with it. I especially like the ACK's on the 1.2 branch: #10 

@nuclearace please feel free to comment and say if you don't think this is needed / would help much with getting better connectivity to the server under certain conditions.

And thanks for starting a cool project.

**Comment by nuclearace** [comment]
I'd have to research it a bit, but I think it would require quite a bit of work. I know that I'd have to change parsing and sending messages, since I built it around SocketRocket/WebSockets.

**Comment by naartjie** [comment]
Okay, thanks, so you do think it's worth it, but it's not an easy/straightforward fix.

What can I do to help?

**Comment by nuclearace** [comment]
I think it would be worth it in the long-run. I just have to figure out what needs to change/added to support fallback.

**Comment by nuclearace** [comment]
@naartjie check out the polling branch

**Comment by naartjie** [comment]
@nuclearace 
Oh wow, cool, I will check it out, and let you know. Thanks!!

**Comment by nuclearace** [comment]
It'll also fix a few bugs I found. i.e binary data is actually broken.

**Comment by nuclearace** [comment]
Merged.
