### ISSUE TITLE
dequeueInput - allocate region error code 3

### ISSUE THREAD

**Issue by Saulenco** [nuclearace/Socket.IO-Client-Swift#135]
Hi have some trouble with some big data. 

We send the image throw sockets in base64 format. And some time we receive this crash.
![screen shot 2016-11-23 at 15 49 37](https://cloud.githubusercontent.com/assets/8323284/20564287/3bc16a82-b195-11e6-994f-836f850466fe.png)

is There any way to increase the buffer size to avoid this issue  ?

I changed the  `BUFFER_MAX` to 10000000 but no success.

**Comment by nuclearace** [comment]
No idea, I don't actually maintain the websocket dependency.

**Comment by Saulenco** [comment]
so the solution that @nuclearace showed is [daltoniam/Starscream#289](https://github.com/daltoniam/Starscream/pull/289)
