### ISSUE TITLE
Handshake (connect) with parameters

### ISSUE THREAD

**Issue by markschmid** [nuclearace/Socket.IO-Client-Swift#15]
Enhancement request: It would be nice if there was a second connect() method that takes custom parameters for the handshake. That way, the client could tell the server an auth token or other data it wants the server to know upon connection.

**Comment by nuclearace** [comment]
I'm not sure what you mean. I wasn't aware that socket.io could do that sort of thing

**Comment by markschmid** [comment]
I'm not too sure either. From what I've seen the following iOS library supports something like that:
[socket.IO-objc](https://github.com/francoisp/socket.IO-objc)

```
[socketIO connectToHost:@"localhost"
                 onPort:3000
             withParams:[NSDictionary dictionaryWithObjectsAndKeys:@"1234", @"auth_token", nil]
];
```

Quickly going through the Socket.io docs, I couldn't find anything about it. Probably we'd have to dig through the JS code of Socket.io to find out. Anyway, you're of course right, if Socket.io doesn't support it, it makes no sense. I'll try to find out more.

**Comment by markschmid** [comment]
OK, so after some googling I've found that apparently on the server side it seems like you can access those query parameters in the socket.request object. Like so:

```
io.on('connection', function(socket){
  // console.log(socket.request.foo);
  console.log(socket.request._query);
});
```

We're using Socket.IO-Client-Swift and so far like it a lot. We're not so much into Swift yet, that's why we currently use it from Objective-C. Therefore, can't help with an implementation just now :/

**Comment by nuclearace** [comment]
I'll look into it later today.

**Comment by nuclearace** [comment]
Also it actually works from Objective-C? I didn't explicitly try to make it compatible with Objective-C.

**Comment by nuclearace** [comment]
So `console.log(socket.request._query)` seems to print out the request from 

```swift
"ws://\(self.socketURL)/socket.io/?transport=websocket"
```

The question I guess I have now is, what exactly is breaking? Can you provide some sort of server setup that the client fails to connect to now.

**Comment by markschmid** [comment]
Regarding your question about using the your library in Objective-C: Yes it works. After setting the two-way bridging headers correctly (SocketRocket -> SwiftIO -> our code), we had to make very small adjustments in your code to get it to run.
So far, we've been able to connect and send and receive events just fine. We first tried [SIOSocket](https://github.com/MegaBits/SIOSocket) but its performance seems less good (internally, it's interpreting JavaScript in a UIWebView). The other mentioned iOS library [socket.IO-objc](https://github.com/francoisp/socket.IO-objc) seems to be the oldest (probably used the most). Unfortunately, it's not fully supporting Socket.io 1.0 yet. That's why we're currently trying with your library, even though written in Swift. :)

**Comment by markschmid** [comment]
I don't think anything is breaking at all.

I've just been wondering if there's a way to send data right along with the call that makes the connection. Looking at the headers of your library, the method called "connect" takes no arguments.
[socket.IO-objc](https://github.com/francoisp/socket.IO-objc) on the other hand seems to have two connect methods, one of which takes an NSDictionary with parameters:

```
[socketIO connectToHost:@"localhost"
                 onPort:3000
             withParams:[NSDictionary dictionaryWithObjectsAndKeys:@"1234", @"auth_token", nil]
];
```

So I think what I'm suggesting is just a feature request: to be able to send key/value based data upon connecting. Please excuse, I'm not a specialist in Socket.io, so there's a chance that I'm looking at this in completely wrong way...

**Comment by nuclearace** [comment]
Oh I see. That would be used to specify things like the transport to use, which in this case is locked to websockets, see #13. 

I'll see if this is worth putting in. Right now I'm not sure if it's worth the time.

**Comment by markschmid** [comment]
I'm not 100% sure if it has to do with the question of which transport to use (websockets are fine for us). It would be more something like (speaking Swift, which I don't know):

```
socket.connect(myWhateverData: [
    "foo": "bar",
    "this": "that
])
```

which should probably get translated into something like:

```
ws://<socketURL>/socket.io/?transport=websocket&foo=bar&this=that
```

When I find time I'll look into how [socket.IO-objc](https://github.com/francoisp/socket.IO-objc) does it. Thanks for your time and the cool library!

**Comment by nuclearace** [comment]
Added basic support

**Comment by naartjie** [comment]
Thanks guys. I hacked something quickly because I needed an `authToken` passed as a query parameter on connection. So in `init()` I added:
```swift
            if let query = opts!["query"] as? String {
                self.query = query
            }
```
and later:
```swift
        if self.secure {
            endpoint = "wss://\(self.socketURL)/socket.io/?transport=websocket&\(query!)"
        } else {
            endpoint = "ws://\(self.socketURL)/socket.io/?transport=websocket&\(query!)"
        }
```

I was going to polish it up and submit a PR, but I see I don't need to anynmore ;)

**Comment by naartjie** [comment]
On second thought, maybe adding the second connect method is overkill? Maybe just overloading the current `connect` method is better, using swifts named parameters?

**Comment by markschmid** [comment]
@nuclearace : Thanks a lot! I'll try the new connectWithParams method out asap, it's looking good. Whether or not to overload the existing connect() with named parameters I can't tell. A second method was just the first thing that came into my mind...

**Comment by nuclearace** [comment]
@markschmid Was that method enough?

**Comment by markschmid** [comment]
@nuclearace We've tested it and it works perfectly! You've even thought about urlencoding the params, which is very convenient. So yes, we're very happy :) Thanks again!

**Comment by naartjie** [comment]
@nuclearace the `connectWithParams` works perfectly for me as well, thanks :+1:  I was still using my old patched version, and I forgot all about it when I upgraded to the latest release of this lib when Xcode 6.3 / Swift 1.2 came out, doh! :-0

Might be a little late for this, but I just wanted to chip in: Since we are able to, should the library not try to follow the API of the JS socket.io client? In the JS client, the above would look something like this:

```javascript
var socket = io.connect('http://excample.com', {query:"param1=value"});
```

**Comment by sstadelman** [comment]
@nuclearace Did this not make it into the iOS side of the interface?  

My reading of the API was that I would be able to use the iOS `setOpts` to set these options on the socket, before calling connect.  But, I don't see them in the query on the server side.  I'm not sure if these are *different* options...?

```objc
[self.socket setOpts:@{@"log" : @(YES),
                     @"query" : @{@"token" : [SocketController shared].token}}]; 
[self.socket connect];
```
My expectation is that I should be able to inspect the query and find `token=<myToken>`, but instead I see only the transport and base64 info:  
```
{"transport":"polling","b64":"1"}
```

**Comment by nuclearace** [comment]
There's now an an option for it.

```swift
let socket = SocketIOClient(socketURL: "blah", opts: ["connectParams": ["test": 2]])
```

**Comment by sstadelman** [comment]
I did a little more investigation on this, it looks like the iOS API doesn't contain the `connectWithParams` equivalent; the `initWithSocketURL:options:` takes a nullable dictionary, instead of an array of strings.  These options aren't added as query parameters.
```objC
self.socket = [[SocketIOClient alloc] initWithSocketURL:@"localhost:8091" options:@{@"?token" : [SocketController shared].token}];
```
Result:  `{"transport":"polling","b64":"1"}`

I mucked around with setting these parameters directly to the `socketURL:`, but this seems to results in some unhanded duplication.  These were my results:
```objc
initWithSocketURL:@"localhost:8091/socket.io/?transport=polling&b64=1&token=<myToken>"
```
Result:  `{"transport":"polling","b64":["1","1"],"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaXJzdF9uYW1lIjoiU3RhbiIsImxhc3RfbmFtZSI6IlN0YWRlbG1hbiIsImVtYWlsIjoic3Rhbi5zdGFkZWxtYW5Ac2FwLmNvbSIsImlkIjoxMjMsImlhdCI6MTQ0MTc2MDU5MCwiZXhwIjoxNDQxNzc4NTkwfQ.atShU5i6xGOz6RVmKg5nTnrDp4NAYNd12bemWIDMk_s/socket.io/?transport=polling"}`

```objc
initWithSocketURL:@"localhost:8091/socket.io/?token=<myToken>"
```
Result:  No connection to server, client error:  
`ERROR SocketEngine: Parsing error: {"code":0,"message":"Transport unknown"}`

**Comment by sstadelman** [comment]
@nuclearace thanks for looking at this... I'm not exactly sure what I'm seeing yet, but I'm looking at the generated **<Socket_IO_Client_Swift/Socket_IO_Client_Swift-Swift.h>** interface, and this is the generated declaration for **SocketIOClient**

```objc
SWIFT_CLASS("_TtC22Socket_IO_Client_Swift14SocketIOClient")
@interface SocketIOClient : NSObject <SocketEngineClient>
@property (nonatomic, readonly, copy) NSString * __nonnull socketURL;
@property (nonatomic, readonly) dispatch_queue_attr_t __null_unspecified handleAckQueue;
@property (nonatomic, readonly) dispatch_queue_attr_t __null_unspecified handleQueue;
@property (nonatomic, readonly) dispatch_queue_attr_t __null_unspecified emitQueue;
@property (nonatomic, readonly) BOOL closed;
@property (nonatomic, readonly) BOOL connected;
@property (nonatomic, readonly) BOOL connecting;
@property (nonatomic) SocketEngine * __nullable engine;
@property (nonatomic, copy) NSString * __nonnull nsp;
@property (nonatomic, copy) NSDictionary * __nullable opts;
@property (nonatomic) BOOL reconnects;
@property (nonatomic, readonly) BOOL reconnecting;
@property (nonatomic) NSInteger reconnectWait;
@property (nonatomic, readonly) BOOL secure;
@property (nonatomic, readonly, copy) NSString * __nullable sid;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithSocketURL:(NSString * __nonnull)socketURL options:(NSDictionary * __nullable)options;
```

This last method is the `initWithSocketURL:` exposed to Objective-C, which bizarrely takes a NSDictionary.  Can't imagine why yet, since I can see in **SocketIOClient.swift** the following inits:

```objc
public init(var socketURL:String, opts:[String: AnyObject]? = nil) {}
// and
public convenience init(socketURL:String, options:[String: AnyObject]?) {
        self.init(socketURL: socketURL, opts: options)
    }
```
weird. I'll look at how that type could be getting messed up

**Comment by nuclearace** [comment]
It's because of how Swift code bridges to Objective-C. It converts the more type safe Swift type into an NSDictionary. And the naming comes from the convention for Objective-C initializers.

**Comment by sstadelman** [comment]
Victory, using the following.  Much appreciated.

```objc
self.socket = [[SocketIOClient alloc] initWithSocketURL:@"localhost:8091" 
                                                            options:@{@"connectParams" : @{@"token" : [SocketController shared].token}}];
```
```
query: 
   { transport: 'polling',
     token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaXJzdF9uYW1lIjoiU3RhbiIsImxhc3RfbmFtZSI6IlN0YWRlbG1hbiIsImVtYWlsIjoic3Rhbi5zdGFkZWxtYW5Ac2FwLmNvbSIsImlkIjoxMjMsImlhdCI6MTQ0MTc2Mjg5NiwiZXhwIjoxNDQxNzgwODk2fQ.8l9jP7lrlmrWce_calbglnHI18Qf29PTds67CROwuq0',
     b64: '1' } }
```

**Comment by cesar-oyarzun-m** [comment]
Hi @nuclearace I'm trying to connect to the socket with token but is not working, maybe is the syntax here is my code

    public var socket = SocketIOClient(socketURL: "develop.test.com:9000", options: ["log": true,"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiOTllZDUxM2UtZGZhOS00ODU4LWJlYTItODg5MDgxZTUxYzk0Iiwic2VjcmV0IjoiOTQyYmQzYTliYzkxMTBkZTcyZmQwYmUyMzRiNDlhMzUzM2M0MGEwNGFmMTJkNTI0ODYzYmYwNDdhYWJlZjY5ZTBjNTQ3YTljNWNiMDA4MTI3ODBkMmMzNWEwNDJlNTg3In0.6UC_P09W0-mcztRNQpPXep-k8knS5JE1AjSJIY70_C0"])

**Comment by nuclearace** [comment]
How are you doing this with the JavaScript client

**Comment by nuclearace** [comment]
The second one should be the correct way if you're trying to send some connection parameters

**Comment by cesar-oyarzun-m** [comment]
here is the how I'm doing on JS

    socket = io(options.host, {
    forceNew: true,
    query: 'token=' + options.token,
    reconnection: true,
    reconnectionDelay: 1000,
    reconnectionDelayMax: 20000,
    timeout: 20000,
    reconnectionAttempts: Infinity
     });

**Comment by nuclearace** [comment]
connectParams should work. Have you tried debugging what the server is getting? Or do you not have access

**Comment by cesar-oyarzun-m** [comment]
I will try to get access to the server and see if is something there thanks!!

**Comment by cesar-oyarzun-m** [comment]
@nuclearace works perfect thanks! it was something in my end!!

**Comment by sumeshshivan** [comment]
connectParams is not working since I updated to swift 2.0 version of Socket.IO-Client-Swift. 
I tried both 

NSDictionary *dict = [NSDictionary dictionaryWithObjectsAndKeys:queryDict, @"connectParams", nil];
delegate.socketClient = [[SocketIOClient alloc] initWithSocketURL:url options:dict];

and

[delegate.socketClient.engine setConnectParams:queryDict];
[delegate.socketClient connect];

Is there is something I am doing wrong?
