### ISSUE TITLE
Example Project

### ISSUE THREAD

**Issue by eugenpirogoff** [nuclearace/Socket.IO-Client-Swift#18]
Is there any possibility to get an example Project ?

**Comment by nuclearace** [comment]
I'll try to put something together.

**Comment by nuclearace** [comment]
https://github.com/nuclearace/CytubeChatiOS is what I made the client for originally. It's using an older version of socket.io-client, but it still shows basic principles.

**Comment by nuclearace** [comment]
https://github.com/nuclearace/CytubeChatiOS/blob/1.1/CytubeChat1.0/CytubeRoom.swift is the most important class.

**Comment by nuclearace** [comment]
@eugenpirogoff https://github.com/nuclearace/socket.io-client-swift-example
