### ISSUE TITLE
Support for Rooms

### ISSUE THREAD

**Issue by dondreytaylor** [nuclearace/Socket.IO-Client-Swift#19]
First off, thanks for building a client like this it's extremely useful and much needed. So I'm building an application which deals with using SocketIO rooms and I was wondering if this is possible using this Client. Looking through the source code I noticed there was a joinNamespace function but I couldn't find a join function that handled rooms and I was wondering if one existed .

**Comment by nuclearace** [comment]
I'll look into adding it.

**Comment by nuclearace** [comment]
From the socket.io docs it looks like rooms are something done on the server side. I'll keep looking into it though

**Comment by nuclearace** [comment]
@dondreytaylor It seems to already work with rooms, since that's something done via the server.

**Comment by dondreytaylor** [comment]
Thanks for the quick reply. I got rooms to work. You were spot on it's done via the server not the client. Bit of confusion on my part.

**Comment by i-am-chris** [comment]
how to join a room with the client via obj-c?
