### ISSUE TITLE
Socket Id

### ISSUE THREAD

**Issue by markschmid** [nuclearace/Socket.IO-Client-Swift#20]
Appreciating the latest changes a lot, it makes using the library a lot easier with Objective-C.
The socket id property ("sid") of the SocketIOClient object (of which we're making use in our project) seems to be null all the time. From looking at the source, it seems like it's not set anywhere anymore. Is it possible to get the socket id somehow?

**Comment by nuclearace** [comment]
Should be fixed

**Comment by markschmid** [comment]
Perfect, thanks!

**Comment by markschmid** [comment]
There's one more issue that has apparently been fixed: we've run into a lot of "we're in a bad state" situations with 1.1.1, but with 1.1.3 is seems fixed... Cool, thanks :)

**Comment by nuclearace** [comment]
Yeah there was a bug in 1.1.1 where it was polling once after it had upgraded, so it would timeout and cause it to try and reconnect.
