### ISSUE TITLE
"Guaranteed" callback for emit

### ISSUE THREAD

**Issue by markschmid** [nuclearace/Socket.IO-Client-Swift#23]
The following is not an issue, but maybe a feature request:

Let's say in the context of a chat we want to show the user the state of the messages he sends (e.g. "sending", "received by server", "failed transmission" etc.). We're using the emitWithAck: method making use of the acknowledgement callback to determine whether the server has received the message. If so, we can change the state of the message in the UI from "sending" to "received".

In a lot of cases, this works fine. But there are situations, where the ack callback is never called (for instance due to a lossy networks that mobile devices may find themselves in from time to time). The problem is now: When and how do we know that the transmission of that specific message has failed so we can show that to the user in the UI?
As far as I have understood socket.io so far, the protocol does not provide mechanisms to cope with this situation, though not too sure. This is in contrast to let's say AFNetwork where either the success or the error callback block will always be called.

I'm assuming we would need to implement some kind of queue to keep track of the messages that we emitted and at every emit: we'd have to start a timer that after let's say 20seconds will decide whether the emit has been acknowledged and if not, we'd mark the message as "failed transmission".

Another solution could be a variant of the emitWithAck: method where the (ack) callback will be always called (guaranteed): either with the ack from the server, or (after a configurable timeout) with the timeout event. Someone has done something like this for node.js: https://www.npmjs.com/package/timeout-callback

What do you think about it in general (am I missing something here)?
Any chances your client library could provide this convenience?

**Comment by nuclearace** [comment]
I think it would be a variant of emitWithAck. I'll need to think about the best way to implement something like that though.

**Comment by nuclearace** [comment]
Is c17767111224390a1891fd21755af73da75a0a23 what you're thinking of?

**Comment by markschmid** [comment]
Yes, I've tested it and it seems to work exactly as wished for. Thanks a lot!

**Comment by markschmid** [comment]
Quick question regarding the interface changes of Version 2.
The following is the example of emitWithAckObj from your Readme. Could you extend the example showing where the timeout block (the block that is executed when the ack does not arrive but the timeout is reached) would go?
Thanks in advance.

```
[socket emitWithAckObjc:@"ackack" withItems:@[@1]](10, ^(NSArray* data) {
  NSLog(@"Got ack");
});
```

**Comment by nuclearace** [comment]
The callback function and the timeout function are the same thing. However, if it is a timeout the data array will have a single string "NO ACK". Unless I've broke it

**Comment by markschmid** [comment]
Got it, thanks.

**Comment by DevelopscriptLLC** [comment]
In Swift is there any other method for emitWithAck without timeout parameter.
emitWithAck(event:String, _ items:AnyObject...) -> (timeout:UInt64, callback:(NSArray?) -> Void) -> Void - Sends a message that requests an acknowledgement from the server.

I am getting No ACK response after a long time while using this method.
