### ISSUE TITLE
Error in groups

### ISSUE THREAD

**Issue by badescuga9** [nuclearace/Socket.IO-Client-Swift#26]
Hi! First of all thanks for making this library, i've been very happy with it. I just made a pull (commit c6d0331d50df58109a7d3aef7d1eadf454f42fe9) and am getting "error in groups". Know something about this?

**Comment by nuclearace** [comment]
Oh, I need to update 1.2. It's because of #24 most likely

**Comment by nuclearace** [comment]
@badescuga9 try now

**Comment by nuclearace** [comment]
Actually, nvm. I need to change things inside of SocketFixUTF8.swift

**Comment by badescuga9** [comment]
Just tried it, yea, socketfixutf8 needs some work






—

**Comment by nuclearace** [comment]
Latest commit should work. Unless there's other things that changed in master that I missed

**Comment by badescuga9** [comment]
tried it, no more compilation errors but i'm still getting Error in groups

**Comment by nuclearace** [comment]
uncomment https://github.com/nuclearace/Socket.IO-Client-Swift/blob/1.2/SwiftIO/SocketParser.swift#L193 and post what the message looks like that's failing

**Comment by badescuga9** [comment]
30[{"code":"200","message":{"textMessage":"login succesful!","id":"2"}}]

**Comment by nuclearace** [comment]
So it's an ack

**Comment by badescuga9** [comment]
yes, it is :)

**Comment by nuclearace** [comment]
Okay I see why it's happening.

**Comment by badescuga9** [comment]
Awesome! :d






—

**Comment by nuclearace** [comment]
It'll be later today before I can fix it.

**Comment by nuclearace** [comment]
@badescuga9 did that fix it

**Comment by badescuga9** [comment]
Thanks, it now seems to parse, but i've got another problem. Gonna open another report
