### ISSUE TITLE
ack parse problem

### ISSUE THREAD

**Issue by badescuga9** [nuclearace/Socket.IO-Client-Swift#27]
Ok, so i've got a weird issue. Don't know if it's the device or not but i'm getting a very strange outcome:

first, when i run in the simulator, the ack executes just fine. I've commented the NSLog so i can see the parsed string:

31[{"OK":"200","FAIL":"500","code":"200","message":[{"registeredContacts":[{"password":"688274158da469097c6c766277fac272","phone_number":"+31322323","created_at":null,"updated_at":null,"email":"aaa@yahoo.com","id":"2","push_notification_token":"<1234>","device_id":"2323232"}]},{"groups":[{"admin_id":"2","created_at":"2015-03-16T19:22:57.747Z","updated_at":"2015-03-16T19:22:57.747Z","id":"230"}]},{"groupsMembers":[{"groupMember":{"user_name":"Test ","going_status":"going","group_id":"230","user_id":"19","user_phone_number":"+6456546599","created_at":"2015-03-16T19:22:57.759Z","updated_at":"2015-03-16T19:22:57.759Z","id":"287","external_id":"undefined","unreg_user_unique_link":null}},{"groupMember":{"user_name":"badescuga ","going_status":"going","group_id":"230","user_id":"2","user_phone_number":"+654645693","created_at":"2015-03-16T19:22:57.758Z","updated_at":"2015-03-16T19:22:57.758Z","id":"288","external_id":"1180E999-5DC6-415E-B064-D2930D471274","unreg_user_unique_link":null}}]},{"events":[{"admin_id":"2","start_date":"2015-03-16T21:21:33.846Z","end_date":"2015-03-16T21:21:33.846Z","group_id":"230","title":"Testv121","created_at":"2015-03-16T19:22:57.771Z","updated_at":"2015-03-16T19:22:57.771Z","location_id":"","id":"151","location_name":""}]},{"userId":19,"phoneNumber":"+6546453699"}]}]

when i install on the device, the ack doesn't get executed and the swift parse NSLog fires this up:

32[{"code":"200","message":[{"registeredContacts":[{"password":"53df40871f37e91cc85c7a19edc3cfc7","phone_number":"+545354353","created_at":"2015-02-21T18:52:51.743Z","updated_at":"2015-02-21T18:52:51.743Z","email":"zdc@hotmail.com","id":"26","push_notification_token":"<43242 42342 43242 >","device_id":"4343434351217B291A"},{"password":"688274158da469097c6c766277fac272","phone_number":"+445454543699","created_at":null,"updated_at":null,"email":"bfsd@gmail.com","id":"19","push_notification_token":null,"device_id":"F74B850D-AD5C-4042-890D-F1E3471B455D"},{"password":"688274158da469097c6c766277fac272","phone_number":"55344393","created_at":null,"updated_at":null,"email":"dfsfs@yahoo.com","id":"2","push_notification_token":"<30f5eab5 a6cb6654 e5e367bc fe911709 159f9221 22c774f1 ffd5eee8 c9d01e72>","device_id":"424324234"}]},{"groups":[{"admin_id":"2","created_at":"2015-03-16T19:22:57.747Z","updated_at":"2015-03-16T19:22:57.747Z","id":"230"},{"admin_id":"2","created_at":"2015-03-16T20:00:58.163Z","updated_at":"2015-03-16T20:00:58.163Z","id":"231"}]},{"groupsMembers":[{"groupMember":{"user_name":"Test ","going_status":"going","group_id":"230","user_id":"19","user_phone_number":"+40724263699","created_at":"2015-03-16T19:22:57.759Z","updated_at":"2015-03-16T19:22:57.759Z","id":"287","external_id":"undefined","unreg_user_unique_link":null}},{"groupMember":{"user_name":"badescuga ","going_status":"going","group_id":"230","user_id":"2","user_phone_number":"+3424323693","created_at":"2015-03-16T19:22:57.758Z","updated_at":"2015-03-16T19:22:57.758Z","id":"288","external_id":"434234234-D2930D471274","unreg_user_unique_link":null}},{"groupMember":{"user_name":"badescuga ","going_status":"going","group_id":"231","user_id":"2","user_phone_number":"+42343263693","created_at":"2015-03-16T20:00:58.174Z","updated_at":"2015-03-16T20:00:58.174Z","id":"289","external_id":"193A3A8E-D1C1-4E5F-84A3-744495C686BE","unreg_user_unique_link":null}}]},{"events":[{"admin_id":"2","start_date":"2015-03-16T21:21:33.846Z","end_date":"2015-03-16T21:21:33.846Z","group_id":"230","title":"Testv121","created_at":"2015-03-16T19:22:57.771Z","updated_at":"2015-03-16T19:22:57.771Z","location_id":"","id":"151","location_name":""},{"admin_id":"2","start_date":"2015-03-16T21:59:21.478Z","end_date":"2015-03-16T21:59:21.478Z","group_id":"231","title":"aici e un test","created_at":"2015-03-16T20:00:58.180Z","updated_at":"2015-03-16T20:00:58.180Z","location_id":"","id":"152","location_name":""}]},{"userId":2,"phoneNumber":"+42142141241"}]}]

Note: the accounts i'm testing are different so that's why te actual text (the json being sent) is different. The device is iPhone6(iOS,8.2), if that actually matters.

**Comment by nuclearace** [comment]
That's really weird. It shouldn't matter what device it's running on

**Comment by nuclearace** [comment]
Does it happen every time?

**Comment by badescuga9** [comment]
Yes, every time :/



—

**Comment by nuclearace** [comment]
Are you setting the ack timeout to 0?

**Comment by badescuga9** [comment]
Nu, i'm actually setting the timeout to 15000. Could this be an issue?



—

**Comment by nuclearace** [comment]
It'd be nice to have a simpler ack that still fails to parse.

**Comment by badescuga9** [comment]
i've checked, setting to 0 doesn't help. 

I've also noticed another thing though. On the device, i do an extra emit with ack (push notification id which isn't present on the simulator). 

Before the not-processed ack "32[...]" call, i receive an ack that is parsed confirming the notification which has also 32 in front ( 32[{}] --- it's an empty return, can't verify now if it's a bug or not on my part).

I'm not sending the notification id and see that it's all working ok now. Still, it's very weird. I'll return with more details later :)

**Comment by nuclearace** [comment]
Oh okay, the extra emit might be what's going on.

**Comment by nuclearace** [comment]
Right I see what's going on. It'll be a few hours before I can fix it properly.

**Comment by nuclearace** [comment]
Have a solution, just needs more testing

**Comment by nuclearace** [comment]
Basically it's because if you send two emitWithAcks right after another, the first ack will get the wrong ack number.

**Comment by nuclearace** [comment]
@badescuga9 can you confirmed fixed

**Comment by badescuga9** [comment]
yes, it seems to work! I'll keep testing it.. i got like 2-3 cases out of 20 where the client didn't connect, but if it persists, il return with concrete data.. i can't confirm that the swift-io library was the problem or my code
