### ISSUE TITLE
Basic Auth/Tokens

### ISSUE THREAD

**Issue by gazzer82** [nuclearace/Socket.IO-Client-Swift#28]
Hi,

Using this currently without auth and it's working well. 

We are planning to use basic auth or JSON tokens to secure our rest API. 

Is there, or are there any plans to integrate auth into this framework?

Thanks

Gareth

**Comment by nuclearace** [comment]
There's multiple ways of telling the server stuff during the handshake portion of the connection. See `connectWithParams` or you can try and use cookies

**Comment by nuclearace** [comment]
Or if you can show me a native socket.io-client way of doing it, I can try and add it
