### ISSUE TITLE
Engine crashes when parsing message. 

### ISSUE THREAD

**Issue by miradesne** [nuclearace/Socket.IO-Client-Swift#33]
when engine gets empty message with type 3, it crashes with BAD_ACCESS at socketEngine.swift line 466 after removing message type.

related code:
// Remove message type
        message.removeAtIndex(message.startIndex)
        dispatch_async(self.client.handleQueue) {[weak self] in
             self?.client.parseSocketMessage(message)
             return
        }

as long as you add a message.length check to the message after you remove the message type it will not crash.

**Comment by nuclearace** [comment]
Line 466 is no longer that. https://github.com/nuclearace/Socket.IO-Client-Swift/blob/master/SwiftIO/SocketEngine.swift#L491

**Comment by miradesne** [comment]
yes it's should be line 491. 466 was the old line number before I pulled

**Comment by nuclearace** [comment]
Does it still happen after that last commit

**Comment by miradesne** [comment]
No. It looks like that it's fixed. Thanks!
