### ISSUE TITLE
Modify socket request.

### ISSUE THREAD

**Issue by trungnguyen1791** [nuclearace/Socket.IO-Client-Swift#34]
Currently. With default init func, my socket will have URI like that
" http://my.ip:port/socket.io/?transport=polling&b64=1"

Now i want to modify my URI to 
" http://my.ip:port/socket.io/a_modify/?transport=polling&b64=1"

How i can get this ?

**Comment by nuclearace** [comment]
How would you do it with socket.io-client?

**Comment by nuclearace** [comment]
Currently that's not something that's you can change.

**Comment by trungnguyen1791** [comment]
With socket.io-obj for Objective c. It will give me URI like 
"http://my.ip:port/socket.io/1/?t=1427860212243"

May be i missing something in the configuration step, then the "/1" didn't appear?
( Sorry for my bad at English)

**Comment by nuclearace** [comment]
the socket.io/1/ scheme is for socket.io < 1.0

**Comment by trungnguyen1791** [comment]
Oh i see. Thanks for save my days.
