### ISSUE TITLE
No such module 'Socket_IO_Client_Swift'

### ISSUE THREAD

**Issue by mcallis** [nuclearace/Socket.IO-Client-Swift#36]
I copied the SocketIOClientSwift folder into my Xcode project
and the import Socket_IO_Client_Swift in the swift file.

**Comment by nuclearace** [comment]
If you copied the folder then you can simply

```swift
let socket = SocketIOClient(socketURL: "localhost:8080")
```

The import is for people who used cocoapods

**Comment by mcallis** [comment]
Thanks for your quick response, but still not working.
Now, in the socket variable, tells unresolved identifier using 'SocketIOClient'
My steps have been updated xcode 6.3, download your library and drag the socketIOClient folder in my project.

**Comment by nuclearace** [comment]
Did you add the source files to your target?

**Comment by nuclearace** [comment]
![](https://i.imgur.com/VGHsbND.png)

**Comment by mcallis** [comment]
It works!
Thank you very much

**Comment by bvcsu** [comment]
I tried loading the framework through pods and I'm having trouble?  I can't get the main program to see the Pod classes.
![image](https://cloud.githubusercontent.com/assets/2301179/7738566/0b8115e0-ff0b-11e4-9e20-1bd8b05e410e.png)

**Comment by nuclearace** [comment]
Hm, I'm getting an error too.

**Comment by nuclearace** [comment]
Actually, it went away if I build the Pods.framework.

**Comment by conandi** [comment]
Hi, I try to use Pod to do that, but the error is: " No such module 'SocketIO'", my Xcode version is 7.3.1

**Comment by nuclearace** [comment]
Be sure to check the readme for the last version that supports 7.3.1. That version should have the framework under that name.

**Comment by conandi** [comment]
Thanks! I solve that problem by updating pod and redo pod install.

**Comment by AnkiReddyPolu** [comment]
i am getting error in no such module socketio pls help me!

**Comment by conandi** [comment]
Can you try to use latest cocoa pod? I think they has fixed this problem.

Thanks.

**Comment by AnkiReddyPolu** [comment]
thank you for given suggestion i have solved problem to import frameworks. again one more problem plese help me i have taken 


//
//  Connection.swift
//  SocketCommunication
//
//  Created by Devendranath on 02/07/17.
//  Copyright © 2017 Devendranath. All rights reserved.
//

import UIKit

class Connection : NSObject, StreamDelegate {
    let serverAddress: CFString = "35.154.61.129" as CFString
    let serverPort: UInt32 = 9000
    weak var delegate: HomeViewController?
    
    private var inputStream: InputStream!
    private var outputStream: OutputStream!
    
    
    init(delegate: HomeViewController) {
        self.delegate = delegate
    }
    func connect() {
        var readStream:  Unmanaged<CFReadStream>?
        var writeStream: Unmanaged<CFWriteStream>?
        
        CFStreamCreatePairWithSocketToHost(nil, self.serverAddress, self.serverPort, &readStream, &writeStream)
        
        self.inputStream = readStream!.takeRetainedValue()
        self.outputStream = writeStream!.takeRetainedValue()
        
        self.inputStream.delegate = self
        self.outputStream.delegate = self
        
        self.inputStream.schedule(in: .current, forMode: .defaultRunLoopMode)
        self.outputStream.schedule(in: .current, forMode: .defaultRunLoopMode)
        
        self.inputStream.open()
        self.outputStream.open()
    }
    
    func joinChat()
    {
        let response = "i am AnkiReddy"
        let data: Data = response.data(using: .ascii)!
        let values = [UInt8](repeating:0, count:data.count)
        outputStream.write(values, maxLength: data.count)
        
        DispatchQueue.main.async {
            if self.outputStream.streamStatus == .open
            {
                print("Sending text when opened")
                self.outputStream.write(values, maxLength: data.count)
            }
        }
        
        DispatchQueue.main.async {
            
        }
    }
    
    func sendMessage(bookDict: Dictionary<String, Any>)
    {
        
        let bookNowDict: [String: Any] = [ "sender_type": bookDict["sender_type"]!,"content_type": bookDict["content_type"]!,"data":[["from_rid": bookDict["from_rid"]!, "to_rid": bookDict["to_rid"]!,"lat": bookDict["lat"]!, "long": bookDict["long"]!,"pickupAddress": bookDict["pickupAddress"]!, "destinationAddress": bookDict["destinationAddress"]!,"preference": bookDict["preference"]!, "driver_id": bookDict["driver_id"]!,"doctor": bookDict["doctor"]!]]] as [String : Any];
        
        var jsonData: Data = NSKeyedArchiver.archivedData(withRootObject: bookNowDict)
        jsonData = try! JSONSerialization.data(withJSONObject: bookNowDict, options: .prettyPrinted)
        let jsonString = String(data: jsonData, encoding: String.Encoding(rawValue: String.Encoding.ascii.rawValue))
        print(jsonString!)
        
        
        let filePath = URL.init(fileURLWithPath: Bundle.main.path(forResource: "Message", ofType: "json")!)
        do {
            let jsonString = try String(contentsOf: filePath, encoding: .utf8)
            let values = [UInt8](repeating:0, count:jsonString.characters.count)
            outputStream.write(values, maxLength: jsonString.characters.count)
        } catch {
            print("Found error:")
        }
    }
    
    func stream(_ aStream: Stream, handle eventCode: Stream.Event) {
        switch eventCode {
        case Stream.Event.openCompleted:
            print("Open completed")
        case Stream.Event.hasBytesAvailable:
            print("hasBytesAvailable")
            var data = Data()
            let bufferSize = 1024
            let buffer = UnsafeMutablePointer<UInt8>.allocate(capacity: bufferSize)
            while inputStream.hasBytesAvailable {
                let read = inputStream.read(buffer, maxLength: bufferSize)
                data.append(buffer, count: read)
            }
            do{
                let json = try JSONSerialization.jsonObject(with: data, options: .allowFragments)
                self.delegate?.messageReceived(response: json)
            }
            catch
            {
                print("Error occurred during extracting")
            }
            
            // let str: NSString = NSString(bytes: UnsafePointer<UInt8>(buffer) + 28, length: Int(buffer[27]), encoding: String.Encoding.utf8.rawValue)!
            buffer.deallocate(capacity: bufferSize)
        case Stream.Event.hasSpaceAvailable:
            print("hasSpaceAvailable")
        case Stream.Event.errorOccurred:
            print("errorOccurred")
        case Stream.Event.endEncountered:
            print("endEncountered")
        default:
            print("Default")
        }
    }
}
 i will send request to server there is no string is taken garbage character how i will solve that problem please help me 
![screen shot 2017-07-25 at 11 37 57 am](https://user-images.githubusercontent.com/29113492/28604846-7a9aac52-71eb-11e7-8d10-0c99d7392ecd.png)
