### ISSUE TITLE
I cannot send complex json object

### ISSUE THREAD

**Issue by meidikawardana** [nuclearace/Socket.IO-Client-Swift#38]
I tried to run this:

self.socket.emit("message","{\"content\":[[null,\"meidika\",\"test\",null,3,1429631885,10776,0,\"0161809001429095521_meidika_cropped.png\",0,[],0,0,\"\",0,3,1429631640,[],[],0,0,1429631885,1]]}")

no error, but the data didn't accepted by server (node js) neither.

the same code works fine on browser (using javascript version, same as server). if I am trying to send that data using json, like the example, say

let myJSON = [
    "name": "bob"
]

socket.emit("jsonTest", myJSON)

(quoted from http://socket.io/blog/socket-io-on-ios/#more-674), it produces error because the data is too complex to be interpreted by the library or by swift.

Please help me.. I have been finding for this problem for hours without success..
thank you, and sorry for my bad english

**Comment by nuclearace** [comment]
Are you literally trying to send 

```swift
"{\"content\":[[null,\"meidika\",\"test\",nul...
```

Because that will just send a string. In order to send json you have to use a Dictionary/NSDictionary/Array like 

```swift
socket.emit("update", ["amount": cur + 2.50, "thing": 234])
```

**Comment by meidikawardana** [comment]
thanks for your fast response. yes, I am trying to send the data as a string literal, because I cannot send it using array either. I changed the code as below:

                            self.socket.emit("message post",[
                                "content": [
                                    [
                                        nil,
                                        "meidika",
                                        "test7",
                                        nil,
                                        3,
                                        1429631885,
                                        10776,
                                        0,
                                        "0161809001429095521_meidika_cropped.png",
                                        0,
                                        [
                                            
                                        ],
                                        0,
                                        0,
                                        "",
                                        0,
                                        3,
                                        1429631640,
                                        [
                                            
                                        ],
                                        [
                                            
                                        ],
                                        0,
                                        0,
                                        1429631885,
                                        1
                                    ]
                                ]
                                ])

but the xcode says an error: '_' is not convertible to 'StringLiteralConvertible', at beginning of this line:

 "content": [

. I dont know what it means..

**Comment by nuclearace** [comment]
Oh okay, I forgot about this. It's because you're using nil inside the array. You have to use `NSNull`

```swift
let dict = [
    "content": [
        [
            NSNull(),
            "meidika",
            "test7",
            NSNull(),
            3,
            1429631885,
            10776,
            0,
            "0161809001429095521_meidika_cropped.png",
            0,
            [
                
            ],
            0,
            0,
            "",
            0,
            3,
            1429631640,
            [
                
            ],
            [
                
            ],
            0,
            0,
            1429631885,
            1
        ]
    ]
]
```

**Comment by meidikawardana** [comment]
thanks, sir it is work. but my real problem is, I dont have the raw data. I must get the data from a JSON, because the data is sent from server. so I use SwiftyJSON to parse the data. after the data parsed and inserted one by one, an error happen.
the code: 

var error: NSError?
var dataFromNetwork:NSData! = responseMsg.dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: true)  //responseMsg is an NSString type, with value: "[[null,\"meidika\"]]"

let jsonContent = JSON(data: dataFromNetwork)  //jsonContent is assigned as SwiftyJSON JSON type
let replier : NSString? = jsonContent[0][0].string
let poster : NSString? = jsonContent[0][1].string

let jsonDict = ["content" :
    [
        [
            replier
            ,poster
        ]
    ]
]

self.socket.emit("message post",jsonDict) //--> error: cannot invoke 'emit' with an argument list of type '(String, [String : Array<Array<NSString?>>])'

the error is triggered on the last line of the code.

I am sorry if this is a different issue. I will create a new issue if you say so.

![screen shot 2015-04-22 at 12 08 48 am](https://cloud.githubusercontent.com/assets/2024380/7258196/23753b5a-e885-11e4-90de-5d5d0e9294cc.png)

**Comment by nuclearace** [comment]
You should use type inference, it's awesome.

I think the real problem is swiftyJSON. I looked into at one point, and realized I don't like it. I do all json parsing with NSJSONSerialization. 

But your problem here is optionals. The client can't handle optionals right now. A better solution is

```swift
let replier = jsonContent[0][0] as? String ?? ""
let poster = jsonContent[0][1] as? String ?? ""

let jsonDict = ["content" :
    [
        [
            replier
            ,poster
        ]
    ]
]
```

This API sounds badly designed.

**Comment by nuclearace** [comment]
Or you can do

```swift
let jsonDict = ["content" :
    [
        [
            replier ?? NSNull()
            ,poster ?? NSNull()
        ]
    ]
]
```

**Comment by meidikawardana** [comment]
thanks, sir. looks like I am back on the right direction with your answers. I will continue the work tommorow. it is already 1:26AM here. I will inform about the result & my solutions in this thread when I get it.

**Comment by meidikawardana** [comment]
@nuclearace , if I use this:

let jsonDict = ["content" :
    [
        [
            replier ?? NSNull()
            ,poster ?? NSNull()
        ]
    ]
]

there are no error in code. but when I click run button on xcode, the build process stuck and never finish.

**Comment by meidikawardana** [comment]
@nuclearace , I finally work it around like this:

                            var replier : NSString = "null"
                            if let replierTemp : NSString? = jsonContent[0][0].string {
                                replier = replierTemp!
                            }

let jsonDict = ["content" :
                                [
                                    [
                                        replier                                       
                                    ]
                                ]
                            ]

                                self.socket.emit("message post",jsonDict)

I decided to adapt the javascript client to treat "null" same as it treat null . fortunately the code I must adapt only a few. maybe you should handle optional swift value in this library. 

thanks for your help. cheers

**Comment by nuclearace** [comment]
I'll think about it.

**Comment by Xaekai** [comment]
For the love of god @meidikawardana see that link [Markdown supported](https://guides.github.com/features/mastering-markdown/) on the reply box?

Click it. At least learn how to use ``` to start and end code blocks.

**Comment by nuclearace** [comment]
Yeah, I don't think optional support is something I want to try and support. It'll just add a bunch of bloat. Because Swift isn't a dynamic language, you'd have to do a bunch of type checking.
