### ISSUE TITLE
Importing into Objective-C, header not found?

### ISSUE THREAD

**Issue by danielwmsun** [nuclearace/Socket.IO-Client-Swift#39]
Manually imported files into my project, made sure they were added to the target and exist in Compile Sources.

Trying to import "SocketIOClient-Swift.h" as per instructions from the link provided to Apple's documentation  but it doesn't work. I've set "Define Modules" in Build Settings to be "Yes" as well. 

How do I import the files into my project?

**Comment by nuclearace** [comment]
If you manually added them then you'll need to

'''Objective-c
 #import "youprojectname-Swift.h"
'''

**Comment by nuclearace** [comment]
You can see what it's named in the build settings

![](https://i.imgur.com/MoeFvYW.png)

**Comment by danielwmsun** [comment]
Ahh, I had tried to do YOUR product name, instead of mine.

Thank you.
