### ISSUE TITLE
How to connect to certain namespace?

### ISSUE THREAD

**Issue by blackbumer** [nuclearace/Socket.IO-Client-Swift#4]
I wonder how to connect to any namespace besides "/".

**Comment by nuclearace** [comment]
What do you mean?

I would think you could connect to any url that is the socket url of the site. "https://ssl.someplace.com:8080/" , "http://example.com/socket/". However it's up to you to get the url.

I haven't exactly tested that though. If you can provide a url that doesn't work I can look into it.

**Comment by nuclearace** [comment]
Working on it

**Comment by nuclearace** [comment]
Added support for namespace in the latest release.
