### ISSUE TITLE
SecRandomCopyBytes issue when switching Swift 1.2

### ISSUE THREAD

**Issue by mikezucc** [nuclearace/Socket.IO-Client-Swift#40]
Figured its an obvious fix but it had me baffled until I noticed the error >.< long day lmao

Swift 1.2 uses func SecRandomCopyBytes(rnd: SecRandomRef, count: Int, bytes: UnsafeMutablePointer<UInt8>) -> Int32 rather than func SecRandomCopyBytes(rnd: SecRandomRef, count: UInt, bytes: UnsafeMutablePointer<UInt8>) -> Int32

So just change the UInt(sizeof(UInt32)) to Int(sizeof(UInt32))

**Comment by nuclearace** [comment]
What

**Comment by nuclearace** [comment]
Can you explain where you're getting this error? Because I've not seen any warnings or errors

**Comment by mikezucc** [comment]
there was a distinction between Uint and Int being taken as parameters to this function. thats all

**Comment by nuclearace** [comment]
It should've be fixed in the latest version a while ago.
