### ISSUE TITLE
Unexpectedly found nil while unwrapping an Optional Value

### ISSUE THREAD

**Issue by steven10172** [nuclearace/Socket.IO-Client-Swift#43]
I'm fairly new to iOS, but wrote my first app in swift today and it seems that ~5-10% of the time I open the app it crashed with the following error

I'm running Xcode 6.3.1 (Swift 1.2)

![](http://i.imgur.com/0tOG0Jw.png)

**Comment by nuclearace** [comment]
Try using the latest version

**Comment by nuclearace** [comment]
Should have been fixed in https://github.com/socketio/socket.io-client-swift/issues/70
