### ISSUE TITLE
Error message file extension type not supported

### ISSUE THREAD

**Issue by Silvering** [nuclearace/Socket.IO-Client-Swift#45]
Hi,
I'm trying to implement this library to my swift project. I have a server application listening on the port 5260 and waiting for message.
When I start the app the server start the connection but immediately I got this error message : file extension type not supported : .//socket.io/?transport=polling&b64=1

Any idea?
Thx!

**Comment by nuclearace** [comment]
How are you creating the client?

**Comment by Silvering** [comment]
let socket = SocketIOClient(socketURL: "192.168.1.19:5260")
override func viewDidLoad() {
        super.viewDidLoad()
        self.socket.connect()
}

**Comment by nuclearace** [comment]
Is the client giving the error or the server?

**Comment by Silvering** [comment]
The server is giving the message. It's a server running on a windows local machine. It's waiting for commands, I just want to via my iPad app send an emit("hello") and receive this message on the server app.

**Comment by nuclearace** [comment]
What version of socket.io is it using?

**Comment by Silvering** [comment]
The last one from the github page's project. I copied the SocketIOClientSwift folder into my Xcode project.

**Comment by nuclearace** [comment]
I mean what version is the server running?

**Comment by Silvering** [comment]
The server is not using socket.io in a server developed in C language

**Comment by nuclearace** [comment]
Wait what? The client is expecting to be connecting to a socket.io server, or one that follows the socket.io-protocol.

**Comment by Silvering** [comment]
Ah ok..... So this is the problem.. The server is not using the socket.io-protocol.

**Comment by nuclearace** [comment]
Were you expecting a WebSockets client?

**Comment by Silvering** [comment]
yes...

**Comment by nuclearace** [comment]
Well, if you copied the folder into your project https://github.com/daltoniam/Starscream should already be exposed.

**Comment by Silvering** [comment]
Ok thanks for your help!
