### ISSUE TITLE
Initial connection timeout

### ISSUE THREAD

**Issue by bluemasterflows** [nuclearace/Socket.IO-Client-Swift#46]
There appears to be no timeout specifiable for the initial connection: 
[self.socket connectWithParams:@{@"token":token, @"mac":mac}];

Every request after that (emitWithAck) takes a timeout which is great. 
The initial request takes a reconnectWait option, but that only applies after the first connection fails, and the first connection's timeout appears to be 75 seconds, and it's uncustomizable. 

Am I overlooking something?

**Comment by nuclearace** [comment]
The initial timeout is governed by whatever the default timeout is for NSURLRequest I think.

**Comment by nuclearace** [comment]
Well, the initial engine connection that is

**Comment by bluemasterflows** [comment]
Thanks for the quick response! As a quick stop-gap it might be okay if you exposed a property in SocketIOClient or SocketEngine that allows you to set a timeout which would be applied to the NSURLSession's timeoutIntervalForRequest property.

**Comment by nuclearace** [comment]
@bluemasterflows 

```swift
 socket.connect(timeoutAfter: 1) {
    println("failed to connect")
}
```

or Objective-C

```objective-c
[socket connectWithTimeoutAfter:5 withTimeoutHandler:^{
    NSLog(@"Client failed to connect");
}];
```

Worth noting that I've removed connectWithParams. Instead you pass those when you make the socket

**Comment by bluemasterflows** [comment]
Awesome, thanks!

**Comment by rdougan** [comment]
@nuclearace I've noticed a weird case where I'm calling connectWithTimeout:5 - but closing the socket before the timeout ends. This means the timeout handler is still being called. Is this by design?

**Comment by nuclearace** [comment]
Fixed in https://github.com/nuclearace/Socket.IO-Client-Swift/commit/6fa5ce9168059c09f9aa36f1d966a26baa90ac82

**Comment by rdougan** [comment]
Thanks Erik
