### ISSUE TITLE
recognize if socket has been connected successfully

### ISSUE THREAD

**Issue by demonaro** [nuclearace/Socket.IO-Client-Swift#48]
I am new to swift and socket.io and am following your example given here. Following is the code am using to create a socket:

        let socket = SocketIOClient(socketURL: "http://52.someIP.237:8100")
        socket.connect()

But how do I recognise whether the socket is successfully connected or not? Through debugging I got to know that open method is called in SocketEngine.swift but it returns after executing the following code:

`self.session.dataTaskWithRequest(reqPolling) {[weak self] data, res, err in
            var err2:NSError?
            if self == nil {
                return                // returns here
            } else if err != nil || data == nil {   // executes first
                self?.handlePollingFailed(err)
                return
            }
`
And in res object I get :

`<NSHTTPURLResponse: 0x7fa321718790> { URL: http://52.someIP.237:8100/socket.io/?transport=polling&b64=1 } { status code: 200, headers {
    Connection = "keep-alive";
    Date = "Thu, 14 May 2015 08:49:30 GMT";
    "Transfer-Encoding" = Identity;
} }`

Does this mean the socket is cerated and ready? If I specify a wrong URL then also it returns on this very same point.

Please help. Thanks in advance

**Comment by nuclearace** [comment]
socket.io is event driven. Just add a handler for "connect" to know when it is connected.

```swift
socket.on("connect") {data, ack in
    // Code for connect
}
```

**Comment by demonaro** [comment]
Thanks nuclearace, I added:

// Socket Events
        socket.on("connect") {data, ack in
            // Code for connect
             NSLog("socket connected")
        }
socket.connect()

but it still isn't connected.

I debugged and found the following:

public func connect() gets fired -> then `func open(opts:[String: AnyObject]? = nil)` gets fired
Inside `open func`, there is following closure:

{[weak self] data, res, err in
            var err2:NSError?
            if self == nil {
                return
            } else if err != nil || data == nil {
                self?.handlePollingFailed(err)
                return
            }
            
            if let dataString = NSString(data: data, encoding: NSUTF8StringEncoding) as? String {
                let parsed:[String]? = dataString["(\\d*):(\\d)(\\{.*\\})?"].groups()
                
                if parsed == nil || parsed?.count != 4 { // here parsed is always nil n hence it is returned though in the dataString, I get the output: Welcome to socket.io
                    return
                }
                
                let length = parsed![1]
                let type = parsed![2]
                let jsonData = parsed![3].dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)
                
                if type != "0" {
                    NSLog("Error handshaking")
                    return
                }
                
                if let json = NSJSONSerialization.JSONObjectWithData(jsonData!,
                    options: NSJSONReadingOptions.AllowFragments, error: &err2) as? NSDictionary {
                        if let sid = json["sid"] as? String {
                            // println(json)
                            self?.sid = sid
                            self?._connected = true
                            
                            if !self!.forcePolling {
                                self?.ws = WebSocket(url: NSURL(string: urlWebSocket + "&sid=\(self!.sid)")!)
                                self?.ws?.queue = self?.handleQueue
                                self?.ws?.delegate = self
                                self?.ws?.connect()
                            }
                        } else {
                            NSLog("Error handshaking")
                            return
                        }
                        
                        if let pingInterval = json["pingInterval"] as? Int {
                            self?.pingInterval = pingInterval / 1000
                        }
                }
                
                self?.doPoll()
                self?.startPingTimer()
            }}.resume()

In the above code, `parsed` is always nil n hence it is returned though in the `dataString`, I get the output: `Welcome to socket.io`

Where am I getting wrong? How do I solve this?

**Comment by nuclearace** [comment]
What version of socketio is the server using.
