### ISSUE TITLE
Message Sending Failed while sending complex JSON. 

### ISSUE THREAD

**Issue by sauvikatinnofied** [nuclearace/Socket.IO-Client-Swift#49]
In my current project I am sending some string to the socket. When the string is simple (example "Sauvik Dolui"), server is successfully receiving the string. But when I am sending a complex JSON string like 

{
    "placeID": "554c547a079c79dc3c71572b",
    "type": 2,
    "user": {
        "gender": 1,
        "isInvisible": false,
        "lastName": "Dolui",
        "firstName": "Sauvik",
        "profilePicture": "https://.....r.jpg",
        "dob": "1978-05-03T00:00:00.000Z",
        "_id": "55475ed29ee11a140728672f",
        "preferredLanguage": "en-us",
        "isLoggedIn": false,
        "isAlreadyBlocked": false,
        "socialId": "805597032855698",
        "socialType": 1,
        "deviceType": 0,
        "hideName": false,
        "email": "efdolui@example.com",
        "statusText": "Searching for a playground nearby  for playing Football.",
        "visitedCount": 1
    }
} 

then the sending failed.

**Comment by nuclearace** [comment]
You cannot send JSON as a string, it needs to be an NSDictionary/Dictionary

**Comment by nuclearace** [comment]
The client will turn it into a string for you

**Comment by sauvikatinnofied** [comment]
Let me check.

**Comment by sauvikatinnofied** [comment]
Yes, it's now working. Thank you very much. I was working with the issue for last 3 days, did not find out what was the exact problem. Now it working fine. Thank you again.
