### ISSUE TITLE
Connect again after closing socket

### ISSUE THREAD

**Issue by jeon97** [nuclearace/Socket.IO-Client-Swift#5]
When I close the socket and then connect again, my listeners are called twice. I know that in the readme it says the socket shouldn't reconnect after closing, but is there any way to fix this? Thank you!

**Comment by nuclearace** [comment]
I'll look into it

**Comment by nuclearace** [comment]
If it is still happening now, something is adding the handlers to the socket again.

**Comment by jeon97** [comment]
solved with the close(fast:true) feature
