### ISSUE TITLE
socket.on('disconnect', function(data)){} not called.

### ISSUE THREAD

**Issue by sauvikatinnofied** [nuclearace/Socket.IO-Client-Swift#50]
In my project first I am connecting to the main socket server. After that a new room dynamically created in server side. I receive the name of that room. I then set the socketIOClient's namespace to that one, and call joinnamespace(). When I am leaving the room, I set the namespace of socket client as '/' and call joinnamespace() again. But in server side socket.on('disconnect', function(data)){} is not called. Please advice me to leave a dynamically created namespace so that socket.on('disconnect', function(data)){}  is called in server side. Thanks in advance.

**Comment by nuclearace** [comment]
I didn't anticipate someone doing this, and I didn't design the client to handle dynamic namespaces. I probably need to send a disconnect packet on the namespace

**Comment by nuclearace** [comment]
Actually, right now setting nsp to / and calling joinNamespace does nothing but let the client receive events from the root namespace again.

**Comment by nuclearace** [comment]
Added a quick fix into v2.3.1. You can just call `socket.leaveNamespace()` to leave the namespace and go back to root. I'm going to redo namespace support soon.

**Comment by sauvikatinnofied** [comment]
Thank you so much for your quick support. Let me use that <code>socket.leaveNamespace()</code>, then I am informing you, the response from server.

**Comment by sauvikatinnofied** [comment]
@nuclearace , it is now woking fine. Hope to get support from you in future. Thank you again.
