### ISSUE TITLE
Remote server connection error?

### ISSUE THREAD

**Issue by Dmurph24** [nuclearace/Socket.IO-Client-Swift#53]
I am trying to connect a socket to my remote server with the following syntax:
<code>let socket = SocketIOClient(socketURL: "my.server.com:port")</code>
I have tried this with and without the port referenced and `http://` added

When I call <code>socket.connect()</code> I receive the following errors:
>SocketClient: Adding handler for event: connect
>SocketClient: Adding handler for event: error
>SocketClient: Adding engine
>SocketEngine: Starting engine
>SocketEngine: Handshaking
>SocketEngine: Doing polling request
>ERROR SocketClient: Error: Could not connect to the server.
>SocketClient: Handling event: error with data: Optional([Could not connect to the server.])

I am 100% certain that the server is handling appropriately. I did notice all the examples given using this library are using `localhost` instead of a remote server connection. Something else to note is that the server is hosted by heroku. However, we have an equivalent app that is for android which connects to it just fine.

Is anyone able to explain why I am having this issue?

**Comment by nuclearace** [comment]
What version is the server running?

**Comment by Dmurph24** [comment]
The server is running on version 1.3.5 for socket.io, the newest version

**Comment by nuclearace** [comment]
Would you be able to provide your server url? Because I'm able to connect to my test server fine.

**Comment by nuclearace** [comment]
The only thing I've noticed is if you pass http:// or leave out the https:// when the port is actually tls.

**Comment by Dmurph24** [comment]
spotbox.herokuapp.com is the server name. We were able to connect to the socket with just this information on the android library for socket.io

**Comment by nuclearace** [comment]
Oh, you might need to actually specify the socket.io url.

**Comment by nuclearace** [comment]
Including the port.

**Comment by nuclearace** [comment]
Wait, nvm. I think I can connect.

**Comment by nuclearace** [comment]
![](https://i.imgur.com/Hr21ZLB.png)

**Comment by Dmurph24** [comment]
So the problem was I needed the extra parameters? Can you explain? I will try this out when I have my laptop handy.

**Comment by nuclearace** [comment]
You shouldn't need them, since those are the default, they're just there for testing.

**Comment by nuclearace** [comment]
I'm not sure why it's saying `Could not connect to the server`. I think that's something coming from the Engine here https://github.com/nuclearace/Socket.IO-Client-Swift/blob/master/SocketIOClientSwift/SocketEngine.swift#L360

**Comment by Dmurph24** [comment]
But the connection is working for you? Can you provide your code?

**Comment by Dmurph24** [comment]
I used your parameters and it now is connecting!

**Comment by nuclearace** [comment]
I can provide a base case.

```swift
import Foundation

let socket = SocketIOClient(socketURL: "spotbox.herokuapp.com", options: ["log": true])

socket.on("connect") {data, ack in
    println("socket connected")
}

socket.connect()

CFRunLoopRun()
```

**Comment by nuclearace** [comment]
This assumes you submodule the client, and it's OS X

**Comment by Dmurph24** [comment]
I really have no idea why its working now, because I had exactly this before but its possible I changed one little thing. Most importantly, its working now! Thanks so much for the help!

**Comment by nuclearace** [comment]
No problem.

**Comment by codalamanp** [comment]
How to know if timeout error occurs while connecting the server in this example?

**Comment by RajeshwarSharma** [comment]
I didn't get the correct answer for this.
