### ISSUE TITLE
Swift 2

### ISSUE THREAD

**Issue by nuclearace** [nuclearace/Socket.IO-Client-Swift#56]
Swift 2 broke a lot of things.

**Comment by kdogisthebest** [comment]
Do you mean it broke how the code compiles or how socket.io runs?

**Comment by nuclearace** [comment]
It broke some things. Specifically the old ack emitter used a variadic parameter: `AnyObject...`. That seems to crash the Swift compiler in Swift 2. So I'm using the equivalent `[AnyObject]` . Mild annoyance.

**Comment by kdogisthebest** [comment]
First error I got from your branch was:

SocketClient: Adding handler for event: connect
SocketClient: Adding handler for event: disconnect
SocketClient: Adding engine
SocketEngine: Starting engine
SocketEngine: Handshaking
SocketEngine: Doing polling request
CFNetwork SSLHandshake failed (-9806)
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9806)
An SSL error has occurred and a secure connection to the server cannot be made

Setting self signed certificate = true didn't help either

**Comment by nuclearace** [comment]
Are you using a self-signed cert? You'll need to use the `sessionDelegate: NSURLSessionDelegate` with an object that handles that case.

**Comment by nuclearace** [comment]
Or force websockets

**Comment by kdogisthebest** [comment]
It's not self signed and I'm pretty sure the whole SSL chain is included in the backend

**Comment by nuclearace** [comment]
Are you adding https:// to your url? That's the only the way the client can know to use https

**Comment by kdogisthebest** [comment]
Oh wow! I thought my build was using SSL but this was actually the dev version. It's actually going over http but for some reason the log says it's using SSL

**Comment by kdogisthebest** [comment]
Ok just to confirm. Your branch was working when I just now attempted to connect via SSL. When I tried connecting w/o SSL via http://somesize.com:8080 it instead logged 'SSLHandshake failed' even though I wasn't using SSL. This was a connection I was able to make successfully on the main branch.

**Comment by nuclearace** [comment]
Weird.

**Comment by nuclearace** [comment]
#57
