### ISSUE TITLE
Connection is again and again

### ISSUE THREAD

**Issue by PengsreangSrun** [nuclearace/Socket.IO-Client-Swift#59]
I have been facing connection problem when i try connecting. It is connected but the status started connecting again and again! Please, help me solve this problem

**Comment by nuclearace** [comment]
I need more information. What's your setup?

**Comment by PengsreangSrun** [comment]
@nuclearace I have done with connection but from now I cannot emit data to server by emit method!
Could you solve this problem?

**Comment by PengsreangSrun** [comment]
Can this library support son data for emit?

**Comment by nuclearace** [comment]
If you send a NSDictionary (inside the array if you're using objective-c) then it will be turned into json.
