### ISSUE TITLE
Connection params not working

### ISSUE THREAD

**Issue by Alex-Catchpole** [nuclearace/Socket.IO-Client-Swift#61]
I'm trying to use JSON web tokens to authenticate my socket.io connection. To do this i'm using this:

https://github.com/auth0/socketio-jwt

This requires I send the token in the connection params when I connect to my socket.io server. 
This isn't working even though I believe I'm doing everything right. The problem is client side on the app.

    var sockett = SocketIOClient(socketURL: "192.168.0.3:8000", opts: ["connectParams": ["query": "token=\(token)"]])
       
    sockett.on("error"){data, ack in
        println(data)
    }

    sockett.connect()

It appears the params are never being sent. I always receive the error event which tells me I have not sent the headers required (the token)

I believe I am sending the parameters correctly but feel free to correct me if I'm doing something wrong.

**Comment by nuclearace** [comment]
Have you tried

```swift
var sockett = SocketIOClient(socketURL: "192.168.0.3:8000", opts: ["connectParams": ["token": "\(token)"]])
```

**Comment by nuclearace** [comment]
@Alex-Catchpole does ^ work

**Comment by benedictchen** [comment]
This is also not working for me.  Tried "connectParams" and nothing seems to come through at all.

**Comment by markschmid** [comment]
This is working for me. We're using the Objective-C convenience method.
```
self.socket = [[SocketIOClient alloc] initWithSocketURL:@"http://localhost/" options:@{@"connectParams": @{@"foo": @"bar", @"this": @"that"}}
```
On the server, I see (in socket.request):
```
  _query: 
   { transport: 'polling',
     foo: 'bar',
     this: 'that',
     b64: '1' },
```

**Comment by vijaytholpadi** [comment]
@markschmid +1. Worked for me too!

**Comment by cesar-oyarzun-m** [comment]
@Alex-Catchpole  I have the same issue, Is working to some one??
