### ISSUE TITLE
Crash on ack

### ISSUE THREAD

**Issue by hanssl** [nuclearace/Socket.IO-Client-Swift#63]
I have a basic single page project (objective C).  I added 1 pod to the project.  I created a simple function, configureRealtimeSocket(),  to implement the sample code.  I call this function from the app delegate applicationDidBecomeActive().

I get a crash when the ack() call executes.  I have tried changing the params to this function but I still get a crash regardless.

Also, If I comment out the ack() line or the 'currentAmount' event handler then the socket does not connect.  

I added the [socket onAny...] event handler.  This event handler executes successfully as long as I leave the first 'currentAmount' handler in the code.  The socket does not connect if the first event handler is disabled.

![screen shot 2015-06-29 at 11 49 11 am](https://cloud.githubusercontent.com/assets/649957/8414506/c557a128-1e55-11e5-8966-9a96a06cd44b.png)
![screen shot 2015-06-29 at 11 49 37 am](https://cloud.githubusercontent.com/assets/649957/8414507/c55f01a2-1e55-11e5-827a-46d090900b13.png)

**Comment by nuclearace** [comment]
You're declaring the socket inside of method, this is bad. The socket should always be a property of a class. You should lift the declaration of the socket, and use this method to initialize and add the handlers for the socket, and connect it.

The example in the README is just a simple demo of what you'd do if the socket were global.

**Comment by hanssl** [comment]
Good point.  The explains why the socket was not working when I was not calling the 'on' event handler.    

I moved the socket to a property of the App Delegate.  I still get the crash whenever the 'ack()' is called.

**Comment by nuclearace** [comment]
Do you have a stack trace? And can you turn on logging?

**Comment by hanssl** [comment]
I have logging enabled.  
![screen shot 2015-06-29 at 4 14 20 pm](https://cloud.githubusercontent.com/assets/649957/8419797/03468598-1e7a-11e5-9c2d-5c871b16457a.png)
Here is the status when the crash occurs.

**Comment by nuclearace** [comment]
Weird, looks like a bug I fixed a while ago. But my little Objective-C test project seems to work fine.

![](https://i.imgur.com/Uc1zRQc.png)

**Comment by hanssl** [comment]
I emailed you a project and a process to repeat the behavior I see.

**Comment by nuclearace** [comment]
Ahhh, this is because ack is actually optional. In swift it's easy to guard against this with `ack?(myThing)`

If you're unsure if the event will request an ack you can do `if (ack) {ack()}`

**Comment by nuclearace** [comment]
https://github.com/nuclearace/Socket.IO-Client-Swift/blob/master/SocketIOClientSwift/SocketTypes.swift#L33

**Comment by hanssl** [comment]
Thanks for your help.
