### ISSUE TITLE
SocketEngine: Parsing error

### ISSUE THREAD

**Issue by Wojcik** [nuclearace/Socket.IO-Client-Swift#67]
Hey. I'm trying to connect to 443 port. It was using https://github.com/pkyeck/socket.IO-objc and it was working.
Here is a link I'm trying https://notification-service-my.service.com:443/socket.io/1/?transport=polling&v=102&token=Q2insb1SvQSFivO_rXbIuQ&ctype=mobile

And I'm getting an error : ERROR SocketEngine: Parsing error: zkNtw8QFFgbjqHxhUJpf:60:60:websocket,htmlfile,xhr-polling,jsonp-polling

Thank you

**Comment by nuclearace** [comment]
What version of socket.io is the server running? This library only supports socket.io 1.0+. Also connection parameters would be passed into the socket when you create it.

```swift
let socket = SocketIOClient(socketURL: "https://notification-service-my.service.com:443", opts: [
    "connectParams": [
        "token": token,
        "cType": "mobile"
    ]
])
```

**Comment by Wojcik** [comment]
Argh, I didn't know that the server is using 0.9.11. Thanks for help.
