### ISSUE TITLE
EmitWithAck is not working

### ISSUE THREAD

**Issue by tolgay007** [nuclearace/Socket.IO-Client-Swift#68]
I am trying to run following code:

socket.emitWithAck("ackTest", "test").onAck(0) {data in
      println(data?[0])
}

But I am getting following compiler error:

'OnAckCallback' does not have a member named 'onAck'

How can I fix this?

**Comment by nuclearace** [comment]
```swift
socket.emitWithAck("canUpdate", cur)(timeout: 0) {data in
    println("got ack")
}
```

**Comment by nuclearace** [comment]
That's assuming you have the latest version
