### ISSUE TITLE
Cancel emit/emitWithAck

### ISSUE THREAD

**Issue by luzianscherrer** [nuclearace/Socket.IO-Client-Swift#69]
Once an emit or emitWithAck has been made, is there any way to cancel it?

Let's say I call emit and the network is really slow, so nothing goes out during the next 5 seconds and after 4 seconds I choose to cancel that request. Can that be done?

**Comment by nuclearace** [comment]
Not currently. Is this even possible with the js client?

**Comment by luzianscherrer** [comment]
You're right. That's not a functionality that is available in the js client. So I guess it's always fire and forget.
