### ISSUE TITLE
socket.connected always returns false

### ISSUE THREAD

**Issue by monchoz** [nuclearace/Socket.IO-Client-Swift#70]
Hi,

What's the use of this method since always returns false? Or am I missing something?

**Comment by nuclearace** [comment]
What version of the client are you using? I know there was a bug in an earlier version that made connected broken.

**Comment by monchoz** [comment]
I'm not pretty sure, I downloaded it like a week ago, where can I see the version number?

**Comment by monchoz** [comment]
I think it's v2.4.0

**Comment by nuclearace** [comment]
I think it was fixed in that version, are you checking socket.connected in a `connect` handler?

**Comment by monchoz** [comment]
No, It only works in a connect handler?

**Comment by nuclearace** [comment]
It shouldn't, but does it return false inside of one?

**Comment by monchoz** [comment]
I just did, It's working! I think it always worked, I was calling it in a function of ViewController that executes before where I set socket.connect

Thanks!
