### ISSUE TITLE
Socket.IO-Client-Swift and Watch OS2

### ISSUE THREAD

**Issue by jnormanpg** [nuclearace/Socket.IO-Client-Swift#73]
We are using this library for our watch app, on iOS 8 where the watch extension lives on the iPhone.  With iOS9 and Watch OS2, the extension can be moved to the watch and run natively.  However, we're getting compiler errors as shown by the attached screen shot.  Any plans to migrate/implement/fix this on Watch OS2?

![screen shot 2015-08-25 at 10 54 29 am](https://cloud.githubusercontent.com/assets/3579392/9473385/b6054a2e-4b17-11e5-8a7a-a736efe0447b.png)

**Comment by nuclearace** [comment]
Probably related to https://github.com/socketio/socket.io-client-swift/issues/130
