### ISSUE TITLE
"Use of unresolved identifer 'SocketIOClient'

### ISSUE THREAD

**Issue by Keoni80** [nuclearace/Socket.IO-Client-Swift#76]
Hello, im using Xcode 7 / Swift 2, y drag the folder "SocketIOClientSwift" into my project, but in the line:

class ViewController: UIViewController, UIAlertViewDelegate {
  
    let socket = SocketIOClient(socketURL: "URL") 
i have the error "Use of unresolved identifer 'SocketIOClient'

i do not use pod,, can you show me how use your library? im trying to send UDP messages from the cellphone to my PC,
thanks

**Comment by nuclearace** [comment]
You probably forgot to include the files in your target.

Also, this isn't a raw UDP library, it's for socket.io servers
