### ISSUE TITLE
ack have no member with

### ISSUE THREAD

**Issue by longxianlin** [nuclearace/Socket.IO-Client-Swift#77]
···swift
        socket.on("currentAmount") {data, ack in
            if data != nil {
                if let cur = data![0] as? Double {
                    socket.emitWithAck("canUpdate", cur)(timeoutAfter: 0) {data in
                        socket.emit("update", ["amount": cur + 2.50])
                    }
                    ack?.with("Got your currentAmount", "dude")
                }
            }
        }
···
ack error： have no member with

**Comment by longxianlin** [comment]
change to ack?("Got your currentAmount", "dude")

**Comment by nuclearace** [comment]
You're on an older version of the client if you're getting that error
