### ISSUE TITLE
Carthage simulator support

### ISSUE THREAD

**Issue by Antowkos** [nuclearace/Socket.IO-Client-Swift#83]
I got this warning after use `carthage update`:

`*** WARNING: Skipping build for "iphonesimulator" SDK because the necessary signing identity "Developer ID Application" is not installed`

Please, change code signing identity to iOS Developer for Debug and iOS Distribution for Release, otherwise it's impossible to run app on simulator.

**Comment by nuclearace** [comment]
Have you verified that this is the correct setup for running on sim? I can't get Carthage to run on El Capitan so I can't check

**Comment by nuclearace** [comment]
Should be fixed in last update

**Comment by Antowkos** [comment]
Yes, it's fixed. Thanks
