### ISSUE TITLE
Socket io client can't emit sometimes

### ISSUE THREAD

**Issue by Antowkos** [nuclearace/Socket.IO-Client-Swift#89]
I install this framework via cocoapods and use it in objective-c. Everything works fine, but sometimes the client's status is `SocketIOClientStatusConnected`, but it can't send messages. Server also detect my connection and can send message to me. I use `emit:withItems:` method for sending messages. 

For catching this i implement disconnection on `applicationDidEnterBackground` and connection on `applicationDidBecomeActive`. After that i just minimize and maximize application and try to send message to server. Unfortunately it absolutely random and i can't give you some stable steps for reproducing it.

**Comment by nuclearace** [comment]
Tracking in https://github.com/socketio/socket.io-client-swift/issues/231
