### ISSUE TITLE
Support for off(event:callback:)

### ISSUE THREAD

**Issue by ostap0207** [nuclearace/Socket.IO-Client-Swift#97]
Are you planing to add support for off(event:callback:), so you can delete just specific call back if needed as in JS version?

**Comment by nuclearace** [comment]
That won't be easy since you can't compare functions in Swift

**Comment by ostap0207** [comment]
Would you consider returning some handler object through which you can remove callback if later.

```
var handler = socket.on("event")  { ... }
socket.off("event", handler)
```
