### ISSUE TITLE
Support for selfSignedSSL

### ISSUE THREAD

**Issue by ostap0207** [nuclearace/Socket.IO-Client-Swift#99]
I am getting an error (OSStatus error -9807.) because of self-signed certificates which are not accepted by default.
Looking into WebSocket you are using, it has support for selfSignedSSL, but there is not way to turn it on.
It would be good to add this as connection option.

**Comment by nuclearace** [comment]
Probably will still get yelled at, but I added an option.

**Comment by ostap0207** [comment]
Thanks! It works.
